# Generated by Django 4.2.17 on 2024-12-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_shoppingcart_items_shoppingcartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(related_name='ShoppingCarts', to='catalogue.shoppingcartitem'),
        ),
    ]
