# Generated by Django 4.2.17 on 2024-12-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_billofsale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillOfSale',
            new_name='Receipt',
        ),
    ]
