# Generated by Django 4.2.17 on 2024-12-07 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_rename_billofsale_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 5, 18, 12, 925113)),
        ),
    ]
