# Generated by Django 4.2.17 on 2024-12-07 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_receipt_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
