# Generated by Django 4.2.17 on 2024-12-07 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_alter_receipt_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
