# Generated by Django 4.2.17 on 2025-01-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_product_images_product_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent', models.CharField(max_length=255)),
                ('serialized_shopping_cart', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='phonenumber',
            field=models.CharField(default=2024919813, max_length=30),
            preserve_default=False,
        ),
    ]
