# Generated by Django 4.2.17 on 2025-01-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_billofsale_receipt_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofsale',
            name='stripe_payment_intent',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
