# Generated by Django 4.2.17 on 2025-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_alter_billofsale_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
