# Generated by Django 4.2.17 on 2025-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
