# Generated by Django 4.2.17 on 2025-02-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_alter_sitesetting_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='products/thumbnails'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='products',
            field=models.ManyToManyField(related_name='product_groups', to='catalogue.product'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalogue.product')),
            ],
        ),
    ]
