# Generated by Django 4.2.17 on 2025-02-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_remove_product_thumbnail_url_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='/noimage.png', upload_to='products/thumbnails'),
        ),
    ]
