# Generated by Django 4.2.17 on 2025-02-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='noimage.png', upload_to='products/thumbnails'),
        ),
    ]
