# Generated by Django 4.2.17 on 2025-02-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_remove_shoppingcart_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
